before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: eNHrc69ALTWRC3XxXNVW7fecVFma0c4TLLhxWUjVa+pdYVaoL1Vlsi2rVRNTs1d7x/FpzD/KDv4tu6uDiCycIuMTB/m47j4L/jNKI8GAkCWP7j06qGiY4YI0cQ75iPsvwbtCEsojuIyfqcg3Nbdc339tBuU4/OtIp/f6su3IMmDt05jRoCy/aFHhygwWL1JibiM8+Bsk9buXbzJu8MtQd3x6LqWY9S5yTVHPIf4FQd6aSsL6hJTSuMES5hSP5E+i+OPvvXLoHvwekD+rdS3MUoG5W6Po7iklM7E1U1uI/VaF6qSHHZ9c3n8uy63EvUcNa5Vpwd+hEUiewujTXy958p/21rqUoRGUStlKUqQSoqRN433lEHF2VKxGIAAPbTpAkkNiPTE2bhIJV1giPEwRgKKKJjN2KJkn8OaWFA9XrBvawK0VvfR4pQjm+1T+SCR/XS4VxOBBL4BfWEwd/PBiVokuhfUdes+VavQHCrMxV0SGy/LU4tZ6qmGVQ07Z14gfJWAdGy8jN/cEAGiFP/75RSie+QyJ1wnmB8o7jHgNyd4L9rZaAA/2Bc3RkKqYrxOOvsLBftSaMXQGkCZ48hfKEwyuy+I6rxLguQfIlIpxCyBNUoxg4I5cbb98hDgrw5t9JVy0/3Jt8nuXGmNo+pGVFcbJM2hk+p2vvTx75LK1cMM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
